apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-web-module
spec:
  selector:
    matchLabels:
      app: example-web-module
  replicas: 1
  template:
    metadata:
      labels:
        app: example-web-module
    spec:
      containers:
      - name: example-web-module
        image: example-web-module:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
          - name: nginx-config
            mountPath: /etc/nginx/conf.d/default.conf
            subPath: default.conf
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config