apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      listen 80;

      location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
      }

      location /module/ {
        rewrite ^/module(.*) $1 break;
        proxy_pass "http://web-module.default.svc.cluster.local";
        proxy_redirect off;
      }
    }
